# ==== PROMPT CONFIG ====
right_format="""$aws$os"""
add_newline=false

[git_status]
stashed = "≡"

[aws]
symbol = ' '

[os.symbols]
Debian = " "
Windows = ' '
Arch = '󰣇'
Macos = '󰀵'

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = ""
