(load "~/.config/emacs/emacs.d/options.el")
(load "~/.config/emacs/emacs.d/electric-pair.el")
(load "~/.config/emacs/emacs.d/packages.el")
(load "~/.config/emacs/emacs.d/keybinds.el")
(load "~/.config/emacs/emacs.d/org.el")
(load "~/.config/emacs/emacs.d/dired.el")
;; (load "~/.config/emacs/emacs.d/treesitter.el")
